<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Nice3point.Revit.Api.RevitAPI" Version="2019.*" />
    <PackageReference Include="Nice3point.Revit.Api.RevitAPIUI" Version="2019.*" />
  </ItemGroup>
</Project>
